# Generated by Django 2.1 on 2018-08-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180821_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_creator',
            new_name='creator',
        ),
    ]
